name: Daily FPL Prices
on:
  schedule:
    - cron: "0 22 * * *"   # every day at 16:00 PDT
  workflow_dispatch:     # Allows manual triggering
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests beautifulsoup4
      - run: python fpl_price.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_FPL_PRICE_WEBHOOK }}
